apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-push-secrets.name" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vault-push-secrets.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vault-push-secrets.name" . }}
    spec:
      containers:
        - env:
            - name: BITWARDEN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ required "config.bitwardenAccessTokenSecret is required" .Values.config.bitwardenAccessTokenSecret }}
                  key: {{ required "config.bitwardenAccessTokenKey is required" .Values.config.bitwardenAccessTokenKey }}
            - name: BITWARDEN_SECRET_ID
              value: {{ required "config.bitwardenSecretId is required" .Values.config.bitwardenSecretId }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel }}
            - name: VAULT_ADDR
              value: {{ required "config.vaultAddr is required" .Values.config.vaultAddr }}
            - name: VAULT_AUTH_MOUNT
              value: {{ required "config.vaultAuthMount is required" .Values.config.vaultAuthMount }}
            - name: VAULT_AUTH_ROLE
              value: {{ required "config.vaultAuthRole is required" .Values.config.vaultAuthRole }}
            - name: VAULT_SECRETS_MOUNT
              value: {{ required "config.vaultSecretsMount is required" .Values.config.vaultSecretsMount }}
          image: ghcr.io/benfiola/homelab-images/vault-push-secrets:{{ .Values.deployment.image.tag | default (trimPrefix "v" .Chart.Version) }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pgrep -f "vault-push-secrets" > /dev/null
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          name: pusher
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pgrep -f "vault-push-secrets" > /dev/null
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- if .Values.deployment.resources }}
          resources: {{ .Values.deployment.resources | toYaml | nindent 10 }}
          {{- end }}
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            privileged: false
      serviceAccountName: {{ include "vault-push-secrets.serviceAccountName" . }}
