apiVersion: v2
name: pvc-restore
description: A helm chart that deploys a controller used to enable annotation-based volsync restores on related persistent volume claims.
type: application
version: 0.0.0
appVersion: "0.0.0"
