version: 2

project_name: linstor-provision-disk

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X {{ .ModulePath }}/internal.Version={{ .Version }}

dockers_v2:
  - images:
      - "{{ .Env.IMAGE_BASE }}/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile
    labels:
      org.opencontainers.image.version: "{{ .Version }}"

changelog:
  use: github-native

release:
  footer: |
    **Docker Image:** `{{ .Env.IMAGE_BASE}}/{{ .ProjectName }}:{{ .Version }}`
  name_template: "{{ .ProjectName }}-{{ .Version }}"
