apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pvc-restore.name" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pvc-restore.name" . }}
  replicas: {{ int .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pvc-restore.name" . }}
    spec:
      containers:
        - args:
            - homelab-helper
            - pvc-restore
          {{- $envVars := list }}
          {{- if .Values.config.cacheStorageClass }}
            {{- $envVars = append $envVars (dict "name" "CACHE_STORAGE_CLASS" "value" .Values.config.cacheStorageClass) }}
          {{- end }}
          {{- if gt (int .Values.deployment.replicas) 1 }}
            {{- $envVars = append $envVars (dict "name" "LEADER_ELECTION" "value" "true") }}
          {{- end }}
          {{- if $envVars }}
          env:
          {{- range $envVars }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          image: ghcr.io/benfiola/homelab-helper:{{ .Values.deployment.image.tag | default (trimPrefix "v" .Chart.Version) }}
          name: controller
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- if .Values.deployment.resources }}
          resources: {{ .Values.deployment.resources | toYaml | nindent 10 }}
          {{- end }}          
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            privileged: false
      serviceAccountName: {{ include "pvc-restore.name" . }}
