//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package api

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCOwner) DeepCopyInto(out *PVCOwner) {
	*out = *in
	out.ResourceRef = in.ResourceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCOwner.
func (in *PVCOwner) DeepCopy() *PVCOwner {
	if in == nil {
		return nil
	}
	out := new(PVCOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCRestore) DeepCopyInto(out *PVCRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCRestore.
func (in *PVCRestore) DeepCopy() *PVCRestore {
	if in == nil {
		return nil
	}
	out := new(PVCRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PVCRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCRestoreList) DeepCopyInto(out *PVCRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PVCRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCRestoreList.
func (in *PVCRestoreList) DeepCopy() *PVCRestoreList {
	if in == nil {
		return nil
	}
	out := new(PVCRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PVCRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCRestoreSpec) DeepCopyInto(out *PVCRestoreSpec) {
	*out = *in
	if in.Previous != nil {
		in, out := &in.Previous, &out.Previous
		*out = new(int32)
		**out = **in
	}
	if in.RestoreAsOf != nil {
		in, out := &in.RestoreAsOf, &out.RestoreAsOf
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCRestoreSpec.
func (in *PVCRestoreSpec) DeepCopy() *PVCRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(PVCRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCRestoreStatus) DeepCopyInto(out *PVCRestoreStatus) {
	*out = *in
	if in.PVCOwners != nil {
		in, out := &in.PVCOwners, &out.PVCOwners
		*out = make([]PVCOwner, len(*in))
		copy(*out, *in)
	}
	if in.ReplicationSource != nil {
		in, out := &in.ReplicationSource, &out.ReplicationSource
		*out = new(string)
		**out = **in
	}
	if in.ReplicationDestination != nil {
		in, out := &in.ReplicationDestination, &out.ReplicationDestination
		*out = new(string)
		**out = **in
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(string)
		**out = **in
	}
	if in.LastReconciledTime != nil {
		in, out := &in.LastReconciledTime, &out.LastReconciledTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCRestoreStatus.
func (in *PVCRestoreStatus) DeepCopy() *PVCRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(PVCRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}
