version: 2

project_name: home-assistant

builds:
  - skip: true

dockers_v2:
  - images:
      - "{{ .Env.IMAGE_BASE }}/{{ .ProjectName }}"
    extra_files:
      - rootfs
    tags:
      - "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile
    labels:
      org.opencontainers.image.version: "{{ .Version }}"

changelog:
  use: github-native

release:
  footer: |
    **Docker Image:** `{{ .Env.IMAGE_BASE}}/{{ .ProjectName }}:{{ .Version }}`
  name_template: "{{ .ProjectName }}-{{ .Version }}"
