config:
  cloudflareApiTokenKey: ""
  cloudflareApiTokenSecret: ""
  cloudflareZones: []
  interval: ""
  logLevel: ""
  logFormat: ""
deployment:
  image:
    tag: ""
  resources: null
serviceAccount:
  name: ""
