version: 2

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/main.go
    binary: seven-days-to-die
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/benfiola/homelab-images/seven-days-to-die/internal.Version={{ .Version }}

dockers:
  - image_templates:
      - "ghcr.io/benfiola/homelab-images/seven-days-to-die:{{ .Version }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.version={{ .Version }}"

release:
  github:
    owner: benfiola
    name: homelab-images
  name_template: "seven-days-to-die-{{ .Version }}"
