version: 2

dockers:
  - image_templates:
      - 'ghcr.io/benfiola/homelab-images/lvm2:{{ .Version }}'
    dockerfile: Dockerfile
    build_flag_templates:
      - '--label=org.opencontainers.image.version={{ .Version }}'

release:
  github:
    owner: benfiola
    name: homelab-images
  name_template: 'lvm2-{{ .Version }}'
