version: 2

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/main.go
    binary: vault-push-secrets
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/benfiola/homelab-images/vault-push-secrets/internal/vaultpushsecrets.Version={{ .Version }}

dockers:
  - image_templates:
      - 'ghcr.io/benfiola/homelab-images/vault-push-secrets:{{ .Version }}'
    dockerfile: Dockerfile
    build_flag_templates:
      - '--label=org.opencontainers.image.version={{ .Version }}'

release:
  github:
    owner: benfiola
    name: homelab-images
  name_template: 'vault-push-secrets-{{ .Version }}'
